CREATE DATABASE AplicacionDoctores;
USE AplicacionDoctores;

CREATE TABLE DOCTORES
(
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(100),
APELLIDO VARCHAR(100),
CEDULA VARCHAR(100),
ESPECIALIDAD VARCHAR(100),
EXEQUATUR VARCHAR(100)
);

CREATE TABLE PACIENTES
(
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
CEDULA VARCHAR(100),
NOMBRE VARCHAR(100),
APELLIDO VARCHAR(100),
TIPO_SANGRE VARCHAR(100),
GENERO VARCHAR(100),
FECHA_NACIMIENTO DATE,
ALERGIAS VARCHAR(100),
FOTO LONGBLOB,
ID_DOCTOR INT,
FOREIGN KEY(ID_DOCTOR) REFERENCES DOCTORES(ID)
);

CREATE TABLE CONSULTAS
(
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_PACIENTE INT NOT NULL,
ID_DOCTOR INT NOT NULL,
FECHA DATE,
MOTIVO VARCHAR(200),
SEGURO VARCHAR(100),
MONTO INT,
DIAGNOSTICO VARCHAR(100),
NOTA VARCHAR(100),
EVIDENCIA LONGBLOB,
FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTES(ID),
FOREIGN KEY(ID_DOCTOR) REFERENCES DOCTORES(ID)
);